<?php
/**
 * @author Medust.com
 * Plugin: Ad Box
 */
?>

<div class="postbox">
	<div class="ms-ad-box">
		<h3>Ad Box Plugin to Add Image Ad to your Blog</h3>
        <p>Thank you for using our plugin!</p>
        
        <p><strong>You can customize the widget from post editor for every post of the blog.</strong></p>
        
        <p>To put an ad on your website, just go to <a href="widgets.php">the widgets page</a>, and look for: <strong>Ad Box</strong></p>
        
        
        <p>To use the plugin follow these steps below.</p>
        
        <p><strong>Step 1:</strong> Go to <a href="widgets.php">the widgets page</a>, and look for: <strong>Ad Box</strong>, and add it to your widget area (best to add at the bottom of the sidebar widget area).</p>
        <p><strong>Step 2:</strong> Fill the necessary details, this is the <strong>default ad</strong> for the widget.</p>
        <p><strong>Step 3:</strong> If you want to use <strong>custom ad for any post</strong> of your blog, then go to the editor of the post and at <strong>"Ad Box"</strong> section fill the information.</p>
        
        <p>Here is a demo of the ad generated by the plugin. It will be fixed at top of the screen while scrolling down to the page after its position at widget area.</p>
        
        <div style="width:500px; margin:20px auto;"><img src="<?php echo plugin_dir_url(__FILE__).'../../assets/ad-demo.jpg' ?>" width="100%"></div>
        
    </div>
</div>

</div>